---
- name: restart etherpad
  systemd:
    name: etherpad
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes
    state: restarted
