listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ["10.0.0.3"]

    resources:
{% if synapse_federation_listener %}
      - names: [client, federation]
{% else %}
      - names: [client]
{% endif %}
        compress: false
