---
- name: "add database user {{ etherpad_database_user }}"
  postgresql_user:
    name: "{{ etherpad_database_user }}"
    password: "{{ etherpad_database_password }}"
  become: yes
  become_user: "{{ postgres_database_user }}"
#  delegate_to: "{{ postgres_database_host }}"

- name: "create database {{ etherpad_database_database }}"
  postgresql_db:
    name: "{{ etherpad_database_database }}"
    owner: "{{ etherpad_database_user }}"
    encoding: UTF-8
    lc_collate: C
    lc_ctype: C
    template: template0
  become: yes
  become_user: "{{ postgres_database_user }}"
#  delegate_to: "{{ postgres_database_host }}"
